on:
  issues:
    types: [opened, reopened]

name: Index gypsum project

jobs:
  index-project:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'upload complete' && github.event.issue.user.login == 'ArtifactDB-bot'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache modules
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: node-${{ hashFiles('**/package.json') }}

      - name: Set up Node
        uses: actions/setup-node@v3.4.1

      - name: Install required packages
        run: npm i

      - name: Cache schemas 
        id: cache-schemas
        uses: actions/cache@v3
        with:
          path: schemas/
          key: schemas-${{ hashFiles('**/config.sh') }}

      - name: Download schemas
        if: steps.cache-schemas.outputs.cache-hit != 'true'
        run: |
          source config.sh
          wget $SCHEMA_BUNDLE_URL -O bundle.tar.gz
          tar -xvf bundle.tar.gz
          mv resolved schemas
          rm -rf bundle.tar.gz

      - name: Index project
        run: |
            source config.sh
            node src/index-project.js \
              --cfid $CF_ACCOUNT_ID \
              --r2bucket $R2_BUCKET_NAME \
              --r2key ${{ secrets.R2_ACCESS_KEY_ID }} \
              --r2secret ${{ secrets.R2_SECRET_ACCESS_KEY }} \
              --ghrepo ${{ github.repository }} \
              --ghissue ${{ github.event.issue.number }} \
              --ghtoken ${{ secrets.GH_BOT_TOKEN }} \
              --parameters '${{ github.event.issue.body }}' \
              --schemas schemas
